### PR TITLE
Changes to get OSX Monterey to complete yarn build

### PR DESCRIPTION
**Pull request by bonafideduck**
MacOS Monterey was experiencing compilation errors.  I did the following:

1. `yarn upgrade --latest`
2. Reverted bootstrap and eslint
3. Added `/* @jest-environment jsdom */` to test headers
4. Made some formatting changes to make prettier happy
5. Verified that `yarn test` succeeds.

What I have not done:
1. Any testing other than to see if the extension installs.

### CODE REVIEW

**Comment by bonafideduck** [comment]
This is an example of the OSX build failure:
```
√ tabwrangler % yarn      
yarn install v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > bootstrap@4.4.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.4.1" has unmet peer dependency "popper.js@^1.16.0".
[4/4] 🔨  Building fresh packages...
[-/4] ⢀ waiting...
[2/4] ⢀ fsevents
[-/4] ⢀ waiting...
warning Error running install script for optional dependency: "/Users/markeklund/work/tabwrangler/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments: 
Directory: /Users/markeklund/work/tabwrangler/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@17.5.0 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for \"/Users/markeklund/work/tabwrangler/node_modules/fsevents/lib/binding/Release/node-v102-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.10/fse-v1.2.10-node-v102-darwin-x64.tar.gz
node-pre-gyp http 403 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.10/fse-v1.2.10-node-v102-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(403): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.10/fse-v1.2.10-node-v102-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.10 and node@17.5.0 (node-v102 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 403 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.10/fse-v1.2.10-node-v102-darwin-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@17.5.0 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@17.5.0 | darwin | x64
gyp info find Python using Python version 3.9.10 found at \"/usr/local/opt/python@3.9/bin/python3.9\"
(node:17249) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/markeklund/work/tabwrangler/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/markeklund/work/tabwrangler/node_modules/fsevents/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/markeklund/work/tabwrangler/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/markeklund/Library/Caches/node-gyp/17.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/markeklund/Library/Caches/node-gyp/17.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/markeklund/work/tabwrangler/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/markeklund/Library/Caches/node-gyp/17.5.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/markeklund/work/tabwrangler/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@17.5.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:2884:
../../nan/nan_typedarray_contents.h:34:43: error: no member named 'GetContents' in 'v8::ArrayBuffer'
      data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                  ~~~~~~~~^
1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/markeklund/work/tabwrangler/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.3.0
gyp ERR! command \"/usr/local/Cellar/node/17.5.0/bin/node\" \"/Users/markeklund/work/tabwrangler/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/markeklund/work/tabwrangler/node_modules/fsevents/lib/binding/Release/node-v102-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/markeklund/work/tabwrangler/node_modules/fsevents/lib/binding/Release/node-v102-darwin-x64\" \"--napi_version=8\" \"--node_abi_napi=napi\" \"--napi_build_version=0\" \"--node_napi_label=node-v102\"
gyp ERR! cwd /Users/markeklund/work/tabwrangler/node_modules/fsevents
gyp ERR! node -v v17.5.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/17.5.0/bin/node /Users/markeklund/work/tabwrangler/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/markeklund/work/tabwrangler/node_modules/fsevents/lib/binding/Release/node-v102-darwin-x64/fse.node --module_name=fse --module_path=/Users/markeklund/work/tabwrangler/node_modules/fsevents/lib/binding/Release/node-v102-darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/markeklund/work/tabwrangler/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Darwin 21.3.0
node-pre-gyp ERR! command \"/usr/local/Cellar/node/17.5.0/bin/node\" \"/Users/markeklund/work/tabwrangler/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/markeklund/work/tabwrangler/node_modules/fsevents
node-pre-gyp ERR! node -v v17.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/17.5.0/bin/node /Users/markeklund/work/tabwrangler/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/markeklund/work/tabwrangler/node_modules/fsevents/lib/binding/Release/node-v102-darwin-✨  Done in 15.07s.
```

**Comment by bonafideduck** [comment]
@KTamas @ssorallen, I've done as much with this update as I can without further guidance.  I've actually never used tabwrangler and don't know how my changes may have affected it.

**Comment by KTamas** [comment]
@bonafideduck funnily enough i was literally working on the same thing on like, saturday, and got to almost the point where you are. i tried your branch in chrome and while the extension loads, its broken, almost the same way it was broken when i did this process. i went down the rabbit hole that led me to `react-virtualized` not being up-to-date with react 17 which led to another dependency and that's where i gave up... for now

**Comment by KTamas** [comment]
i think the first thing is to do is this, but try staying on react 16, but i don't yet know when i'll have the time and energy for that, but that's the only pointer i can give to you. also, bootstrap 4 -> 5 is a big change and needs some code changes.

**Comment by bonafideduck** [comment]
@KTamas , I'd be willing to try reverting react to earlier.  Also, my branch from yesterday and my branch from today are different, so if you tested my branch a couple days ago, it has been updated..  I don't know enough about this extension to know what is broken.  Can you tell me the steps to see the issue you are seeing?

**Comment by KTamas** [comment]
@bonafideduck check #371

**Comment by bonafideduck** [comment]
@KTamas , that is an impressive amount of work.

**Comment by ssorallen** [comment]
Thank you for taking a look at this. Can you find out the one library that is breaking the build on OS X Monterey and only update that single one?

Please be careful with a full `yarn upgrade --latest`. This updates major versions on a lot of core libraries, and it seems almost guaranteed to break.

**Comment by bonafideduck** [comment]
Closing because @KTamas had a parallel PR.

**Pull request closed without merging**
