### PR TITLE
Add whitelist feature

### LINKED ISSUE #378: Whitelist feature. Close only tabs from the whitelisted websites.
**Is your feature request related to a problem? Please describe.**
Not a problem. Just the use-case I am looking for is not covered by the current features.

**Describe the solution you'd like**
I would like to whitelist websites that the extension is allowed to close. For example, instead of the extension managing all tabs, I only want it to manage those that I know create clutter for me, like stack exchange. If in the future I see I am opening a lot of elastic.co sites and don't close them, I want to whitelist the extension to close those manually again. At the moment I have a fear the extension will touch something I don't want to be closed. Like a (low prio) tab I have left as a reminder for a day later to have a look at when I have some time.

**Describe alternatives you've considered**
Not sure I understand this section, but the alternative I use now is that when the clutter gets unbearable, I go over all tabs manually and start closing all the stackexchange and other not useful anymore tabs.

### PR DESCRIPTION
**Pull request by funblaster22**
Adds button to settings where if checked, only tabs that are in the whitelist will be automatically closed.

Closes #378

### CODE REVIEW

**Comment by funblaster22** [comment]
That should've resolved the ESLint problem

**Comment by ssorallen** [comment]
Hey thanks for this. I'm back in the mode of working on this project and decided to convert from Flow -> TypeScript. The master branch now is all TypeScript so please take a look.

**Comment by funblaster22** [comment]
Ok, I tested it and this version should actually pass the workflow checks

**Comment by musa-almatri-io** [comment]
Any plan to merge this, I believe it is a useful feature.

**Comment by ssorallen** [comment]
Major changes were made to the project to support Chrome's [Manifest v3](https://developer.chrome.com/docs/extensions/mv3/intro/). This PR will need to be recreated on the latest version of the repo.

**Pull request closed without merging**
