### PR TITLE
Upgrades (WIP)

### PR DESCRIPTION
**Pull request by KTamas**
- [x] upgrade packages
- [x] get rid of webpack
- [x] set up basic Github Actions
- [x] add dummy CircleCI config because I can't disable it for now
- [x] migrate to eslint 8
- [ ] re-add firefox support
- [ ] migrate flow to typescript?
- [ ] react 17 somehow?

### CODE REVIEW

**Comment by bonafideduck** [comment]
On MAC build I see this warning:
```
@parcel/transformer-babel: Parcel includes transpilation by default. Babel config .babelrc includes the following redundant
presets: @parcel/babel-preset-env, @babel/preset-react. Removing these may improve build performance.

  /Users/markeklund/work/tabwrangler/.babelrc:3:6
    2 |   "presets": [
  > 3 |     ["@parcel/babel-preset-env", { "modules": "auto"}],
  >   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^
    4 |     "@babel/preset-flow",
  > 5 |     "@babel/preset-react"
  >   |     ^^^^^^^^^^^^^^^^^^^^^
    6 |   ],
    7 |   "plugins": [

  💡 Remove the above presets from .babelrc
  📝 Learn more: https://parceljs.org/languages/javascript/#default-presets
```

**Comment by ssorallen** [comment]
Can this be split up into smaller commits and smaller pull requests? This is an impressive amount of work, and it would be much easier to review in smaller chunks.

**Comment by ssorallen** [comment]
Several of these commits look like they could be individual pull requests. I can hop in here, cherry pick them, and then create independent PRs if you are okay with that.

**Comment by KTamas** [comment]
@ssorallen yeah feel free to pick it up apart and thanks!

@bonafideduck yeah for now that stays bc of eslint but i'm planning to migrate to typescript

**Comment by bonafideduck** [comment]
@KTamas and @ssorallen what is the current state of this upgrade?  Does it work now, or is it still a work in progress?

On my part, I've done the heavy lifting of converting to use browser instead of chrome and used webextension-polyfill for compatibility.  It builds, passes tests, and my minimal testing isn't showing any errors other than a failure to pull wolff fonts.  The changes are[ here](https://github.com/tabwrangler/tabwrangler/compare/upgrades...bonafideduck:polyfill?expand=1).

**Comment by KTamas** [comment]
@bonafideduck it works but right now it has temporarily dropped support for firefox and @ssorallen said he was gonna separate this PR into a few smaller ones

**Comment by ssorallen** [comment]
Closing this out right now since this PR has not been touched in a while. I'm happy to take any of the additions in this PR in smaller chunks.

Thank you for all of your work, @KTamas.

**Pull request closed without merging**
