### PR TITLE
Add bonus time (1/4 of stale time) each time when you focus tab.

### PR DESCRIPTION
**Pull request by h0x91b**
The idea: if you are a focusing tab then this tab is potentially more important then others in the list.
So I am giving to this tab extra 1/4 of time before closing it.

In case that stale time is already staled a much then it just reset a timer.

### CODE REVIEW

**Comment by KTamas** [comment]
This is an interesting feature, but for it to be considered, it'd have to be at least optional, can you implement that?

**Comment by ssorallen** [comment]
This may benefit from a larger refactor like [Tab Actions](https://github.com/tabwrangler/tabwrangler/discussions/358) that would enable multiple stale time configurations. It may be premature to add this feature before thinking through a better representation of tab rules/actions.

**Comment by KTamas** [comment]
@ssorallen yeah makes sense, should we just close this for now?

**Comment by ssorallen** [comment]
@KTamas I'm okay with that. This is also a very old PR that could use another review and design.

**Pull request closed without merging**
