### PR TITLE
Redux for temporary storage and `chrome.storage.local`

### LINKED ISSUE #113: Auto update options page
I like to leave Tab Wrangler's options page open most of the time. Currently, I have to refresh the page to see newly closed tabs. It would be nice if it automatically updated the list whenever something changed.

Thanks for your attention!

### LINKED ISSUE #157: Incorrect tab list during selection
1. Open the TW popup
2. Select all tabs in the list (via the button)
3. Wait for TW to close a tab in the background
4. Deselect all tabs in the list (via the button)

**Expected:**
The list is deselected with the newly-closed tab at the top

**Actual:**
The list contains only 1 tab... seemingly the oldest one? The data is not actually deleted. If you close the popup and reopen it, the list shows all tabs as expected.

### LINKED ISSUE #216: Incorrect tab disappearing when clicking trash icon
I started deleting various tabs out of my wrangled area and noticed that on more than one occasion, about every 4 to 7 clicks, the tab i chose to delete is not the one that got deleted, this also happens for tabs i click to reopen. What seems to be happening, is i click delete or click on link to reopen, and a DIFFERENT tab gets deleted from the list. the list count goes down by one, the clicked link effectively is no longer under your mouse but one row higher. example: link "how a tv works in slow motion" is under my mouse. I left click the link, and that correct link is placed into a tab. however, the link remains in the wrangled list only one row higher. yet the list is diminished by one. I have not figured out how it decides which link is removed, but it is removing them. When i was in time descending, it removed the top 4 links. I did a search for them, and they are not present. to put it plainly, the link you are manipulating and the link the program decides to remove from the wrangled list is not always the same.

Originally mentioned in #192

### LINKED ISSUE #225: Can't remove individual tabs after restoring another
Not sure about Chrome, but this is happening on Firefox: Open the corral, then restore one or more tabs, then click on the "trash" button of any other item - nothing happens.

Removing tabs will still work by selecting them and then clicking on the trash button that appears at the top.

### PR DESCRIPTION
**Pull request by ssorallen**
This adds a Redux Store as the interface to Tab Wrangler's `chrome.storage.local` access. [redux-persist](https://github.com/rt2zz/redux-persist) manages writing to and reading from the browser's storage when Tab Wrangler is started or a value is changed. The former 'settingsLocal.js' attempted to accomplish something similar, but it was incomplete and littered with race conditions because of the underlying async storage.

There is a mildly risky migration that occurs on first launch of this new version: data from `chrome.storage.local` is migrated to a new key that is managed by redux-persist. I have tested this in both Chrome and Firefox and by upgrading multiple times via building from 'master' and building from this 'redux' branch. Everything works smoothly, but I do not have any automated testing for the upgrade process.

Fixes #113 
Fixes #157 
Fixes #216
Fixes #225

### CODE REVIEW

**Comment by ssorallen** [comment]
I am going to sit on this pull request for a day or two and revisit it to see if I come up with anything I may have missed. This is a big change, especially the migration, so I want to make sure it's right.

**Comment by ingorichter** [comment]
I'll review it later today and provide some feedback. What is the best way to test? Custom profile for Chrome?

**Comment by ssorallen** [comment]
@ingorichter Yes, I always test Tab Wrangler in its own Chrome profile. This is how I've been testing:

1. Export your production Tab Wrangler data to a file
2. Build Tab Wrangler from master and install it in the new Chrome profile
3. Import your prod data into the TW built from master
4. Check out the 'redux' branch and re-build TW
5. Click the refresh button on the chrome://extensions page to reload the test version of TW
    * screen shot 2018-07-17 at 10 07 08 am
    * This simulates the same process that happens when Chrome downloads a new version of an extension from the Chrome Store
6. After the refresh, the migration will have been performed. Make sure Tab Wrangler features are still working (like import/export), and everything works as expected.

**Comment by ssorallen** [comment]
Thank you for the review, @ingorichter 👍

**Comment by ssorallen** [comment]
@ingorichter I'm going to merge this because I've been testing it a lot locally and am confident it's in good shape. If you still get a chance to review it, I'd definitely appreciate it. Instead of checking out master to compare, you can check out the commit that's right before what will be this PR's merge commit, 5cc37cf33f92539543c426b226f1bbd684ac0880:

```
git checkout 5cc37cf33f92539543c426b226f1bbd684ac0880
```

**Comment by ingorichter** [comment]
@ssorallen it looks good to after some days of using it. Well done. 👏

**Pull request merged**
